module.exports = {
    black     : 'color: #000000'
  , red       : 'color: #FF0000'
  , green     : 'color: #00FF00'
  , yellow    : 'color: #FFFF00'
  , blue      : 'color: #0000FF'
  , magenta   : 'color: #FF00FF'
  , cyan      : 'color: #00FFFF'
  , white     : 'color: #FFFFFF'
  , gray      : 'color: #C0C0C0'
  , bgBlack   : 'background: #000000'
  , bgRed     : 'background: #FF0000'
  , bgGreen   : 'background: #00FF00'
  , bgYellow  : 'background: #FFFF00'
  , bgBlue    : 'background: #0000FF'
  , bgMagenta : 'background: #FF00FF'
  , bgCyan    : 'background: #00FFFF'
  , bgWhite   : 'background: #000000'
  , bgGray    : 'background: #C0C0C0'
}